version: 2.1

orbs:
  react: thefrontside/react@0.0.4

workflows:
  push:
    jobs:
      - react/checkout-and-install
      - react/eslint:
          requires:
            - react/checkout-and-install
      - react/stylelint:
          requires:
            - react/checkout-and-install
      - react/test:
          requires:
            - react/checkout-and-install
      - react/build:
          requires:
            - react/checkout-and-install